CREATE TABLE department (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR (60) NOT NULL
    );
    
CREATE TABLE seller (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(80) NOT NULL,
    Email VARCHAR(150) NOT NULL,
    BirthDate DATE NOT NULL,
    BaseSalary NUMBER(7, 2) NOT NULL,
    DepartmentId NUMBER NOT NULL,
    CONSTRAINT fk_department FOREIGN KEY (DepartmentId) REFERENCES department (Id)
    );
    
INSERT INTO department (Name) 
VALUES ('Computers');

INSERT INTO department (Name) 
VALUES ('Electronics');

INSERT INTO department (Name) 
VALUES ('Fashion');

INSERT INTO department (Name) 
VALUES ('Books');

INSERT INTO seller (Name, Email, BirthDate, BaseSalary, DepartmentId) 
VALUES ('João', 'jao@gmail.com', TO_DATE('24/06/2004', 'DD/MM/YYYY'), 2000.0, 1);

INSERT INTO seller (Name, Email, BirthDate, BaseSalary, DepartmentId) 
VALUES ('Maria Green', 'maria@gmail.com', TO_DATE('31/12/1979', 'DD/MM/YYYY'), 3500.0, 2);

INSERT INTO seller (Name, Email, BirthDate, BaseSalary, DepartmentId) 
VALUES ('Alex Grey', 'alex@gmail.com', TO_DATE('15/01/1988', 'DD/MM/YYYY'), 2200.0, 3);

INSERT INTO seller (Name, Email, BirthDate, BaseSalary, DepartmentId) 
VALUES ('Martha Red', 'martha@gmail.com', TO_DATE('30/11/1993', 'DD/MM/YYYY'), 3000.0, 4);

COMMIT;
DESCRIBE seller;
DESCRIBE department;

SELECT seller.*, department.NameDEP AS DepName
FROM seller
INNER JOIN department 
ON seller.DepartmentId = department.IDDEP
WHERE seller.Id = 3;

ALTER TABLE department
RENAME COLUMN NAME TO NAMEDEP;

SELECT * FROM seller;


